<html lang="en"><head><meta content="text/html; charset=utf-8" http-equiv="Content-Type"><meta content="width=device-width, initial-scale=1" name="viewport"><meta content="What do you think of designing API functions to use MonadError to handle errors instead of MonadThrow? I think the former is better because you specify the exact type of the error the API will return." name="description"><link href="https://funprog.srid.ca/haskell/monadthrow-vs-monaderror.html" rel="canonical"><meta property="og:title" content="MonadThrow vs MonadError - Haskell"><meta property="og:site_name" content="Functional Programming Zulip Archive"><meta property="og:type" content="article"><meta property="og:article:section" content="Haskell"><meta property="og:article:modified_time" content="2019-11-25T17:55:38Z"><meta property="og:article:published_time" content="2019-11-24T15:40:05Z"><meta property="og:image" content="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"><title>MonadThrow vs MonadError - Haskell</title><style type="text/css">
div#thesite
{
  font-family   : "Open Sans", sans-serif;
  font-size     : 1em !important;
  margin-top    : 1em;
  margin-bottom : 1em;
}

div#thesite h1
{
  font-family : "Roboto", sans-serif;
  line-height : 1.19999em;
}

div#thesite h2
{
  font-family : "Roboto", sans-serif;
  line-height : 1.19999em;
}

div#thesite h3
{
  font-family : "Roboto", sans-serif;
  line-height : 1.19999em;
}

div#thesite h4
{
  font-family : "Roboto", sans-serif;
  line-height : 1.19999em;
}

div#thesite h5
{
  font-family : "Roboto", sans-serif;
  line-height : 1.19999em;
}

div#thesite h6
{
  font-family : "Roboto", sans-serif;
  line-height : 1.19999em;
}

div#thesite .ui.breadcrumb.rib .section
{
  font-family : "Roboto", sans-serif;
  line-height : 1.19999em;
}

div#thesite .header
{
  font-family : "Roboto", sans-serif;
  line-height : 1.19999em;
}

div#thesite .as-header
{
  font-family : "Roboto", sans-serif;
  line-height : 1.19999em;
}

div#thesite code, pre, tt
{
  font-family : "SFMono-Regular","Menlo","Monaco","Consolas","Liberation Mono","Courier New", monospace;
}

div#thesite .ui.breadcrumb.rib
{
  margin-bottom : 1em;
}



div#thesite .ui.comments.messages .comment .metadata a
{
  color : #808080;
}

div#thesite .ui.comments.messages .comment a.avatar img
{
  height : auto;
}

div#thesite .subtle
{
  color : #808080;
}


div#thesite .messages pre
{
  font-size : 85%;
  overflow  : auto;
  max-width : 100%;
}

div#thesite .messages .message_embed
{
  border-left  : solid 3px #808080;
  padding-left : 0.69999em;
}

div#thesite .messages .message_inline_image img
{
  max-width     : 100%;
  margin-bottom : 1em;
}


/* Generated with Clay, http://fvisser.nl/clay */</style><link href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet"><link href="https://fonts.googleapis.com/css?family=Open+Sans|Oswald&amp;display=swap" rel="stylesheet"><link href="https://fonts.googleapis.com/css?family=Roboto|Open+Sans&amp;display=swap" rel="stylesheet"></head><body><div id="thesite" class="ui text container"><div class="ui violet inverted top attached center aligned segment"><h1 class="ui huge header">MonadThrow vs MonadError - Haskell</h1></div><div class="ui attached segment"><div class="ui message"><p>Welcome to the Functional Programming Zulip Chat Archive. You can join the chat <a href="https://funprog.zulipchat.com">here</a>.</p></div><div class="ui breadcrumb rib"><a href="/" class="section">Home</a><i class="right angle icon divider"></i><a href="/haskell/" class="section">#Haskell</a><i class="right angle icon divider"></i><div class="active section">MonadThrow vs MonadError</div></div><div class="ui comments messages"><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181765444" name="181765444"><div>2019-11-24 15:40:05</div></a></div><div class="text"><p>What do you think of designing API functions to use MonadError to handle errors instead of MonadThrow? I think the former is better because you specify the exact type of the error the API will return.</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181765451" name="181765451"><div>2019-11-24 15:40:23</div></a></div><div class="text"><p>The <code>path</code> library doesn't do this, so I've initiated a discussion there: <a href="https://github.com/commercialhaskell/path/issues/149" target="_blank" title="https://github.com/commercialhaskell/path/issues/149">https://github.com/commercialhaskell/path/issues/149</a></p>
<div class="message_embed"><a class="message_embed_image" href="https://github.com/commercialhaskell/path/issues/149" style="background-image: url(https://avatars3.githubusercontent.com/u/10633049?s=400&amp;v=4)" target="_blank"></a><div class="data-container"><div class="message_embed_title"><a href="https://github.com/commercialhaskell/path/issues/149" target="_blank" title="MonadThrow vs MonadError · Issue #149 · commercialhaskell/path">MonadThrow vs MonadError · Issue #149 · commercialhaskell/path</a></div><div class="message_embed_description">The problem with using MonadThrow is that the caller can theoretically expect just about any exceptions to be thrown. Whereas with MonadError e, the now-small range of errors that the caller can ex...</div></div></div></div></div></div><div class="comment"><a class="avatar"><img src="https://www.gravatar.com/avatar/6eab2de473ce3048d021758fab427b54"></a><div class="content"><a class="author">Lukwago Allan</a><div class="metadata"><a href="#181773484" name="181773484"><div>2019-11-24 19:18:36</div></a></div><div class="text"><p>I tend to prefer <code>MonadError</code>  too, it makes error code/handling more explicit</p></div></div></div><div class="comment"><a class="avatar"><img src="https://www.gravatar.com/avatar/c03b8d34978563858020eff0d14cc17b"></a><div class="content"><a class="author">Alexis King</a><div class="metadata"><a href="#181773858" name="181773858"><div>2019-11-24 19:28:29</div></a></div><div class="text"><p>IMO, they serve different purposes—<code>MonadThrow</code> and <code>MonadCatch</code> are really about dealing with <code>IO</code> exceptions (though they have some other instances), and I mostly avoid <code>MonadThrow</code> because I usually don’t want to use <code>IO</code> exceptions. I’d much rather deal with an API that provides <code>MonadError</code> constraints than one that provides <code>MonadThrow</code> constraints.</p>
<p>That said, it’s worth noting that <code>MonadMask</code> is a different beast: it’s fundamentally something <code>MonadError</code> cannot provide, because <code>MonadMask</code> allows you to implement a <code>finally</code> operation that runs if <em>any monad in the stack</em> causes an abort. For example, if you have <code>ExceptT e IO</code>, <code>Control.Monad.Catch.finally</code> will execute the action whether you raise an <code>IO</code> exception or call <code>throwError</code>. In that sense, <code>MonadMask</code> is “deep” while <code>MonadError</code> is “shallow.” You need <code>MonadMask</code> if you need reliable recovery from aborts; <code>MonadError</code> just won’t cut it.</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181839934" name="181839934"><div>2019-11-25 16:43:26</div></a></div><div class="text"><p>Why does <code>MonadError e m</code> have the functional dependency <code>m -&gt; e</code>?</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/20a04d823b7c3891d78ca5f6a188ccd0e4fc5e3d?version=2"></a><div class="content"><a class="author">TheMatten</a><div class="metadata"><a href="#181840239" name="181840239"><div>2019-11-25 16:46:09</div></a></div><div class="text"><p><span class="user-mention" data-user-id="251311">@Sridhar Ratnakumar</span> From instances it seems like underlying <code>m</code> always determines <code>e</code></p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181840366" name="181840366"><div>2019-11-25 16:47:46</div></a></div><div class="text"><p><del>Well I'm looking at <a href="https://hackage.haskell.org/package/mtl-2.2.2/docs/src/Control.Monad.Error.Class.html#line-134" target="_blank" title="https://hackage.haskell.org/package/mtl-2.2.2/docs/src/Control.Monad.Error.Class.html#line-134">the Either instance</a> - and I don't see <code>Either e</code> determining <code>e</code></del> ... oh wait!</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181843021" name="181843021"><div>2019-11-25 17:17:41</div></a></div><div class="text"><p>Okay this does surprise me at first glance: <a href="/user_uploads/13896/Z30vZQIao81t8F_vSAlup6q9/pasted_image.png" target="_blank" title="pasted_image.png">pasted image</a></p>
<div class="message_inline_image"><a href="/user_uploads/13896/Z30vZQIao81t8F_vSAlup6q9/pasted_image.png" target="_blank" title="pasted image"><img src="/user_uploads/13896/Z30vZQIao81t8F_vSAlup6q9/pasted_image.png"></a></div></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181843288" name="181843288"><div>2019-11-25 17:20:34</div></a></div><div class="text"><p>It is surprising, because here I'm thinking "why doesn't compiler use one instance for the first <code>let</code> statement, and another for the other <code>let</code> statement"</p></div></div></div><div class="comment"><a class="avatar"><img src="https://www.gravatar.com/avatar/d5f51e76392d18898a66faf360be0416"></a><div class="content"><a class="author">Daniel Díaz Carrete</a><div class="metadata"><a href="#181843866" name="181843866"><div>2019-11-25 17:27:47</div></a></div><div class="text"><p>Looks like the type annotation should be in the <code>_</code>s, not on the left side.</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181843949" name="181843949"><div>2019-11-25 17:28:36</div></a></div><div class="text"><p>That's not it.</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181843961" name="181843961"><div>2019-11-25 17:28:47</div></a></div><div class="text"><p>Even this fails: </p>
<div class="codehilite"><pre><span></span><span class="nf">main</span> <span class="ow">::</span> <span class="kt">IO</span> <span class="nb">()</span>
<span class="nf">main</span> <span class="ow">=</span> <span class="kr">do</span>
  <span class="nb">()</span> <span class="ow">&lt;-</span> <span class="n">maybe</span> <span class="p">(</span><span class="n">fail</span> <span class="s">&quot;Invalid&quot;</span><span class="p">)</span> <span class="n">pure</span> <span class="o">$</span> <span class="n">someFunc</span> <span class="o">@</span><span class="kt">Maybe</span>
  <span class="n">_v</span> <span class="ow">&lt;-</span> <span class="n">either</span> <span class="p">(</span><span class="n">fail</span> <span class="o">.</span> <span class="n">show</span><span class="p">)</span> <span class="n">pure</span> <span class="o">$</span> <span class="n">someFunc</span> <span class="o">@</span><span class="p">(</span><span class="kt">Either</span> <span class="kt">MyError</span><span class="p">)</span>
  <span class="n">pure</span> <span class="nb">()</span><span class="p">```</span>
</pre></div></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/20a04d823b7c3891d78ca5f6a188ccd0e4fc5e3d?version=2"></a><div class="content"><a class="author">TheMatten</a><div class="metadata"><a href="#181844426" name="181844426"><div>2019-11-25 17:34:22</div></a></div><div class="text"><p><span class="user-mention" data-user-id="251311">@Sridhar Ratnakumar</span> <a href="https://www.stackage.org/haddock/lts-14.15/mtl-2.2.2/Control-Monad-Error.html#t:MonadError" target="_blank" title="https://www.stackage.org/haddock/lts-14.15/mtl-2.2.2/Control-Monad-Error.html#t:MonadError">https://www.stackage.org/haddock/lts-14.15/mtl-2.2.2/Control-Monad-Error.html#t:MonadError</a> - there's only one instance for <code>Maybe</code> (with <code>()</code>) - but <code>someFunc</code> wants one that uses <code>MyError</code></p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/20a04d823b7c3891d78ca5f6a188ccd0e4fc5e3d?version=2"></a><div class="content"><a class="author">TheMatten</a><div class="metadata"><a href="#181844437" name="181844437"><div>2019-11-25 17:34:37</div></a></div><div class="text"><p>(There can only be one because of fundep)</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181844447" name="181844447"><div>2019-11-25 17:34:49</div></a></div><div class="text"><p>Yea, the question is why is the second invocation not using the Either instance?</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181844457" name="181844457"><div>2019-11-25 17:35:02</div></a></div><div class="text"><p>Why does the compiler not use <em>two</em> instances in the same function (<code>main</code>)?</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181844499" name="181844499"><div>2019-11-25 17:35:42</div></a></div><div class="text"><p>I mean, I explicitly specified <code>Either MyError</code> as the monad in the second invocation; so GHC should have no trouble, in theory, figuring out the right instance to use?</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/20a04d823b7c3891d78ca5f6a188ccd0e4fc5e3d?version=2"></a><div class="content"><a class="author">TheMatten</a><div class="metadata"><a href="#181844561" name="181844561"><div>2019-11-25 17:36:04</div></a></div><div class="text"><p>Error talks about first invocation</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181844767" name="181844767"><div>2019-11-25 17:38:06</div></a></div><div class="text"><p>Uh, right. I didn't see. <code>Maybe</code> was a bad choice.</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181844824" name="181844824"><div>2019-11-25 17:39:11</div></a></div><div class="text"><p>I'm trying to understand the problem Chris points to in the 3rd paragraph of <a href="https://github.com/commercialhaskell/path/issues/149#issuecomment-558069993" target="_blank" title="https://github.com/commercialhaskell/path/issues/149#issuecomment-558069993">https://github.com/commercialhaskell/path/issues/149#issuecomment-558069993</a></p>
<div class="message_embed"><a class="message_embed_image" href="https://github.com/commercialhaskell/path/issues/149#issuecomment-558069993" style="background-image: url(https://avatars3.githubusercontent.com/u/10633049?s=400&amp;v=4)" target="_blank"></a><div class="data-container"><div class="message_embed_title"><a href="https://github.com/commercialhaskell/path/issues/149#issuecomment-558069993" target="_blank" title="MonadThrow vs MonadError · Issue #149 · commercialhaskell/path">MonadThrow vs MonadError · Issue #149 · commercialhaskell/path</a></div><div class="message_embed_description">The problem with using MonadThrow is that the caller can theoretically expect just about any exceptions to be thrown. Whereas with MonadError e, the now-small range of errors that the caller can ex...</div></div></div></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181844931" name="181844931"><div>2019-11-25 17:40:31</div></a></div><div class="text"><p>So if I use a custom error type (<code>MyError</code>) with <code>MonadError</code> - the only instance I use for the <code>m</code> is <code>Either e</code>?</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181844953" name="181844953"><div>2019-11-25 17:41:00</div></a></div><div class="text"><p>(plus, transformer versions)</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/20a04d823b7c3891d78ca5f6a188ccd0e4fc5e3d?version=2"></a><div class="content"><a class="author">TheMatten</a><div class="metadata"><a href="#181845419" name="181845419"><div>2019-11-25 17:46:50</div></a></div><div class="text"><p>You couldn't use it with <code>IO</code>, because <code>IO</code> is bound to <code>IOException</code> (even though it could possibly throw any), while <code>Maybe</code> wouldn't work because it's bound to <code>()</code> (even though you could just ignore error's content and return <code>Nothing</code>)</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181845585" name="181845585"><div>2019-11-25 17:48:42</div></a></div><div class="text"><p>This works: </p>
<div class="codehilite"><pre><span></span><span class="nf">main</span> <span class="ow">::</span> <span class="kt">IO</span> <span class="nb">()</span>
<span class="nf">main</span> <span class="ow">=</span> <span class="kr">do</span>
  <span class="nb">()</span> <span class="ow">&lt;-</span> <span class="n">either</span> <span class="n">throwM</span> <span class="n">pure</span> <span class="n">someFunc</span>
  <span class="kr">let</span> <span class="kr">_</span> <span class="ow">::</span> <span class="kt">Either</span> <span class="kt">MyError</span> <span class="nb">()</span> <span class="ow">=</span> <span class="n">someFunc</span>
  <span class="n">pure</span> <span class="nb">()</span>
</pre></div>


<p>IO and <code>Either e</code> at the same time.</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/20a04d823b7c3891d78ca5f6a188ccd0e4fc5e3d?version=2"></a><div class="content"><a class="author">TheMatten</a><div class="metadata"><a href="#181845652" name="181845652"><div>2019-11-25 17:49:31</div></a></div><div class="text"><p>Actually, now that I think about it - <code>catchError</code> cannot be implemented properly for polymorphic <code>Maybe</code> instance, because you lose original error</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/20a04d823b7c3891d78ca5f6a188ccd0e4fc5e3d?version=2"></a><div class="content"><a class="author">TheMatten</a><div class="metadata"><a href="#181845773" name="181845773"><div>2019-11-25 17:50:10</div></a></div><div class="text"><p>You could <code>Monoid</code> yourself out though if it's content is not important</p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/20a04d823b7c3891d78ca5f6a188ccd0e4fc5e3d?version=2"></a><div class="content"><a class="author">TheMatten</a><div class="metadata"><a href="#181845878" name="181845878"><div>2019-11-25 17:51:13</div></a></div><div class="text"><p>You can have safe <code>MonadThrow e Maybe</code> though because  <code>catch</code> is in <code>MonadCatch</code></p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/20a04d823b7c3891d78ca5f6a188ccd0e4fc5e3d?version=2"></a><div class="content"><a class="author">TheMatten</a><div class="metadata"><a href="#181846167" name="181846167"><div>2019-11-25 17:54:16</div></a></div><div class="text"><p>Think of it this way - <code>MonadError</code> sort of requires <code>m</code> to "keep" original error in case it occurs (<code>catchError</code> is "proof" of that) - this can't be satisfied by <code>Maybe</code> properly<br>
But <code>MonadThrow</code> separates that proof to <code>MonadCatch</code> - so even though <code>Maybe</code> can't have <code>MonadCatch</code> instance, it can have <code>MonadThrow</code></p></div></div></div><div class="comment"><a class="avatar"><img src="https://zulip-avatars.s3.amazonaws.com/13896/4429aa8b689608f24a4ad712843ce29862e330d2?version=3"></a><div class="content"><a class="author">Sridhar Ratnakumar</a><div class="metadata"><a href="#181846314" name="181846314"><div>2019-11-25 17:55:38</div></a></div><div class="text"><p>Yes, but with MonadThrow|Catch we are dealing with bottoms which "bypass" a strict type system.</p></div></div></div></div></div><div class="ui vertical footer segment"><a href="https://github.com/srid/zulip-archive">Powered by Haskell</a> | Questions? Contact <a href="https://www.srid.ca">srid</a></div></div></body></html>